=== Alekseim1500/EpamTask3/periodicals.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<element name="periodicals">
		<complexType>
			<sequence>
				<element name="periodical" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="title" type="string" />
							<element name="type">
								<simpleType>
									<restriction base="string">
										<enumeration value="newspaper" />
										<enumeration value="magazine" />
										<enumeration value="booklet" />
									</restriction>
								</simpleType>
							</element>
							<element name="monthly" type="boolean" />
							<element name="chars">
								<complexType>
									<sequence>
										<element name="color" type="boolean" />
										<element name="volume" type="positiveInteger" />
										<element name="glossy" type="boolean" />
										<element name="subscriptionIndex" type="boolean" minOccurs="0"/>
									</sequence>
								</complexType>
							</element>
						</sequence>
						<attribute name="id" type="string" use="required" />
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== Alekseim1500/EpamTask3/periodicals.xml
<?xml version="1.0" encoding="UTF-8"?>
<periodicals xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="periodicals.xsd">
	<periodical id="a&amp;1">
		<title>Новая Нива</title>
		<type>newspaper</type>
		<monthly>true</monthly>
		<chars>
			<color>false</color>
			<volume>5</volume>
			<glossy>false</glossy>
			<subscriptionIndex>true</subscriptionIndex>
		</chars>
	</periodical>

	<periodical id="a&amp;2">
		<title>Новая Мода</title>
		<type>magazine</type>
		<monthly>false</monthly>
		<chars>
			<color>true</color>
			<volume>20</volume>
			<glossy>true</glossy>
			<subscriptionIndex>false</subscriptionIndex>
		</chars>
	</periodical>

	<periodical id="a&amp;3">
		<title>Италия</title>
		<type>booklet</type>
		<monthly>false</monthly>
		<chars>
			<color>true</color>
			<volume>20</volume>
			<glossy>true</glossy>
		</chars>
	</periodical>
</periodicals>
